name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:permalink
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: //live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : https://assets.webuild.sg/logo-200.jpg
default_day : Sat
default_time : 11am

next_guest: "Emil Tan"
next_episode: "052"
next_podcast_start_time: 2017-11-04 11:00 +0800
next_podcast_end_time: 2017-11-04 12:00 +0800
next_profile: /img/052-emil-tan-profile.jpg
next_topic: Cybersecurity awareness.
next_connect: 'Connect with Emil on <a href="https://twitter.com/Emil0xA">Twitter</a>, <a href="https://www.edgis-security.org/">Edgis Security</a> and <a href="https://www.honeynet.org/">Honeynet Project</a>!'
