name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com (Chinmay and Sayanee)
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: https://live.webuild.sg/feed.xml
destination: ./_publish
permalink: /:permalink
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Chern Jie Lim"
next_episode: "053"
next_podcast_start_time: 2017-12-16 11:00 +0800
next_podcast_end_time: 2017-12-16 12:00 +0800
next_profile: /img/053-chernjie-lim-profile.jpg
next_topic: Git version control.
next_connect: 'Connect with Chern Jie on <a href="https://twitter.com/chernjie">Twitter</a>, <a href="https://github.com/chernjie">GitHub</a> and <a href="https://www.facebook.com/groups/sggrumpygits/">Grumpy Gits</a>!'
