name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com (Chinmay and Sayanee)
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: https://live.webuild.sg/feed.xml
destination: ./_publish
permalink: /:permalink
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Chris Lienert"
next_episode: "053"
next_podcast_start_time: 2018-01-06 11:00 +0800
next_podcast_end_time: 2018-01-06 12:00 +0800
next_profile: /img/053-chris-lienert-profile.jpg
next_topic: CSS in large web apps.
next_connect: 'Connect with Chris on <a href="https://twitter.com/cliener">Twitter</a>, <a href="https://github.com/cliener">GitHub</a> and <a href="https://singaporecss.github.io/">Singapore CSS</a>!'
