name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:permalink
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: http://localhost:4000
timezone:    Asia/Singapore
encoding:    UTF-8

default_logo : logo-100.jpg
default_day : Sat
default_time : 11am

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

next_guest: "Aysha Anggraini"
next_episode: "051"
next_podcast_start_time: 2017-10-14 11:00 +0800
next_podcast_end_time: 2017-10-14 12:00 +0800
next_profile: /img/051-aysha-anggraini-profile.jpg
next_topic: Scalable Vector Graphics (SVG).
next_connect: 'Connect with Aysha on <a href="https://aysha.me/">her blog</a>, <a href="https://twitter.com/renettarenula">Twitter</a> and <a href="https://codepen.io/rrenula/">CodePen</a>!'
